apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    selector: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: https